# Header
menu:
  Home: /
  Archives: /archives

# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
share: 
fancybox: true

# Sidebar
widgets:
- category
- recent_posts
- tag
#- tagcloud
#- search
#- music

# Miscellaneous
google_analytics:
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: 
music: 