aquastyle:
    version: v0.1
    cyanstyle: 
        author: wizardforcel
        version: commit-d37a18d

# Header
menu:
    主页: /
    归档: /archives
    关于: /about.html

# Content
excerpt_link:
prev: 上一页
next: 下一页
reply: 评论
share: 
fancybox: true

# Sidebar
widgets:
- user_widgets
- category
- recent_posts
- tag
#- tagcloud
#- search
#- music
user_widgets:
    Music: <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=298 height=52 src="//music.163.com/outchain/player?type=2&id=1395034165&auto=0&height=32"></iframe>
    Social: |
        <a href="https://github.com/leviolet">Github</a><br/>

# Miscellaneous
google_analytics:
rss:
google_site_verification:
baidu_site_verification:
favicon: /asset/favicon.png
music:
footer_info: |
    © 2020 Leviolet All rights reserved.<br/>
    Powered By: Hexo CyanStyle.<br/>
    Theme: AquaStyle v0.1
    
